name: CI
on:
  schedule:
    - cron: "0 0 * * *"
  push:
  pull_request:
jobs:
  tests:
    runs-on: "ubuntu-latest"
    name: PHP ${{ matrix.php }} - Doctrine ${{ matrix.doctrine }}
    strategy:
      matrix:
        php: ["8.3", "8.4"]
        doctrine: ["2.11", "2.12", "2.13", "2.14", "3.3.1"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: error_reporting=E_ALL
          tools: phpunit, git

      - name: Install Composer dependencies
        run: rm -f composer.lock

      - name: Install doctrine/orm ${{ matrix.doctrine }}
        run: composer require --no-progress --no-scripts --no-plugins doctrine/orm "~${{ matrix.doctrine }}.0" -v

      - name: Update dependencies
        run: composer update --no-interaction

      - name: PHPUnit
        run: vendor/bin/phpunit
