name: CI
on: [push, pull_request]
jobs:
  tests:
    runs-on: 'ubuntu-latest'
    name: PHP ${{ matrix.php }} - doctrine/orm ${{ matrix.orm }}
    strategy:
      matrix:
        php: ['7.2', '7.3', '7.4', '8.0']
        orm: ['2.6.0', '2.7.0', '2.8.0', '2.9.5', '2.11.1']
        exclude:
          - php: '8.0'
            orm: '2.6.0'
          - php: '8.0'
            orm: '2.7.0'
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: phpunit, git

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: "php-${{ matrix.php }}-${{matrix.orm}}-composer-locked-${{ hashFiles('composer.lock') }}"
          restore-keys: "php-${{ matrix.php }}-${{matrix.orm}}-composer-locked-"

      - name: Install Composer dependencies
        run: rm -f composer.lock

      - name: Install doctrine/orm ${{ matrix.orm }}
        run: composer require --no-progress --no-scripts --no-plugins doctrine/orm "~${{ matrix.orm }}" -v

      - name: Update dependencies
        run: composer update --no-interaction

      - name: PHPUnit
        run: vendor/bin/phpunit
